"use client";
import { useState } from "react";
import Navbar from "@/app/components/Navbar";
import Footer from "@/app/components/Footer";
import Link from "next/link";

const faqs = [
  {
    question: "Is Finance Guide completely free to use?",
    answer:
      "Yes, 100% free. There are no hidden charges, no premium plans, and no account creation required. You can generate unlimited budget plans at no cost.",
  },
  {
    question: "Does Finance Guide store my salary or personal data?",
    answer:
      "No. We do not store, log, or transmit any of your personal data. Your salary, name, and family details are used only to calculate your budget in your browser and are never saved anywhere.",
  },
  {
    question: "How accurate is the budget breakdown?",
    answer:
      "The budget uses a weighted allocation algorithm calibrated for Indian cost-of-living realities. It accounts for your city, family size, housing type, transport, and whether you have children. It is not a certified financial plan but is a strong starting point that reflects your actual situation.",
  },
  {
    question: "What is the AI Financial Coach and how does it work?",
    answer:
      "The AI Financial Coach is powered by Google's Gemini AI. After your budget is generated, you can ask it questions like 'Why is my rent allocation so high?' or 'How can I increase my savings?' It answers using your actual budget numbers in simple, jargon-free language.",
  },
  {
    question: "What is the Poverty Escape Roadmap?",
    answer:
      "It is a personalised 6-month financial improvement plan generated by AI based on your salary and current budget. It gives you specific, actionable monthly targets — like how much to cut from food spending or how to start a recurring deposit — all using your real numbers.",
  },
  {
    question: "Why is the AI response sometimes slow?",
    answer:
      "Finance Guide uses Google Gemini's free tier, which allows 10-15 requests per minute. To stay within this limit and keep the app free for everyone, we space out requests automatically. AI responses typically arrive within 6-10 seconds.",
  },
  {
    question: "Can I download my budget plan?",
    answer:
      "Yes. Once your budget is generated, you can download it as a professionally designed PDF that includes your budget breakdown, AI summary, and Poverty Escape Roadmap (if generated). It looks just like the website — navy header, teal accents, and card layout.",
  },
  {
    question: "Does the budget work for all Indian cities?",
    answer:
      "Yes. The algorithm adjusts based on your city input and applies appropriate cost-of-living assumptions. Whether you are in a metro like Mumbai or a smaller city like Patna, the allocations adapt accordingly.",
  },
  {
    question: "What if my actual expenses are very different from the budget?",
    answer:
      "That is completely normal. The budget is a recommended plan, not a reflection of what you currently spend. The goal is to show you what a healthy allocation looks like for your income and situation, and to help you work toward it gradually.",
  },
  {
    question: "Can I use Finance Guide on my phone?",
    answer:
      "Yes. Finance Guide is fully responsive and works on all screen sizes — mobile, tablet, and desktop.",
  },
  {
    question: "Who built Finance Guide?",
    answer:
      "Finance Guide was built by Soumik Majumder, a developer passionate about making financial literacy accessible to everyone in India, especially those who have never had access to financial planning tools.",
  },
];

function FAQItem({ question, answer }: { question: string; answer: string }) {
  const [open, setOpen] = useState(false);
  return (
    <div className="border border-[#dfe6f3] rounded-xl overflow-hidden bg-white">
      <button
        onClick={() => setOpen(!open)}
        className="w-full flex items-center justify-between px-6 py-5 text-left hover:bg-[#f8f9fc] transition-colors"
      >
        <span className="font-semibold text-[#1d3557] text-sm pr-4">{question}</span>
        <span className={`text-[#64ffda] text-lg flex-shrink-0 transition-transform duration-200 ${open ? "rotate-45" : ""}`}>
          +
        </span>
      </button>
      {open && (
        <div className="px-6 pb-5">
          <p className="text-[#4a5568] text-sm leading-relaxed">{answer}</p>
        </div>
      )}
    </div>
  );
}

export default function FAQsClient() {
  return (
    <>
      <Navbar />
      <main>
        <script
          type="application/ld+json"
          dangerouslySetInnerHTML={{
            __html: JSON.stringify({
              "@context": "https://schema.org",
              "@type": "FAQPage",
              mainEntity: faqs.map((faq) => ({
                "@type": "Question",
                name: faq.question,
                acceptedAnswer: {
                  "@type": "Answer",
                  text: faq.answer,
                },
              })),
            }),
          }}
        />
        {/* Hero */}
        <section className="bg-[#0a192f] py-20 px-6 text-center">
          <div className="max-w-2xl mx-auto">
            <h1 className="text-4xl font-bold text-white mb-4">Frequently Asked Questions — Finance Guide</h1>
            <p className="text-[#8892b0] text-lg">
              Everything you need to know about India's free AI budget planner.
            </p>
          </div>
        </section>

        {/* FAQ List */}
        <section className="py-20 px-6 bg-[#f8f9fc]">
          <div className="max-w-2xl mx-auto space-y-3">
            {faqs.map((faq, i) => (
              <FAQItem key={i} question={faq.question} answer={faq.answer} />
            ))}
          </div>

          {/* Still have questions */}
          <div className="max-w-2xl mx-auto mt-14 text-center bg-[#0a192f] rounded-2xl p-10">
            <h3 className="text-white font-bold text-xl mb-3">Still have questions?</h3>
            <p className="text-[#8892b0] text-sm mb-6">
              Reach out to Soumik via email — happy to help.
            </p>
            <a
              href="mailto:soumikmajumder65@gmail.com"
              className="inline-block bg-[#64ffda] text-[#0a192f] font-bold px-8 py-3 rounded-xl hover:bg-[#52e0c4] transition-colors"
            >
              Email Soumik
            </a>
          </div>
        </section>
      </main>
      <Footer />
    </>
  );
}
