import { GovernmentScheme } from "@/app/types/schemes"

export const GOVERNMENT_SCHEMES: GovernmentScheme[] = [
  {
    id: "pmjdy",
    name: "PM Jan Dhan Yojana",
    fullName: "Pradhan Mantri Jan Dhan Yojana",
    category: "savings",
    categoryLabel: "Banking & Savings",
    categoryColor: "text-[#185FA5]",
    categoryBg: "bg-[#E6F1FB]",
    description: "Zero-balance bank account with RuPay debit card, accident insurance of ₹2 lakh, and overdraft facility up to ₹10,000.",
    keyBenefit: "Free bank account + ₹2 lakh accident insurance + ₹10,000 overdraft",
    maxBenefitAmount: 200000,
    benefitLabel: "Up to ₹2 lakh accident cover",
    eligibility: {
      maxAnnualIncome: 9999999,
      maritalStatus: "any",
      housingStatus: "any",
    },
    howToApply: "Visit any bank branch or business correspondent with Aadhaar and one photo. Account opens same day in most cases.",
    documentsNeeded: ["Aadhaar card", "One passport size photo"],
    officialLink: "https://pmjdy.gov.in",
    isNational: true,
  },
  {
    id: "pmay",
    name: "PM Awas Yojana",
    fullName: "Pradhan Mantri Awas Yojana (Urban)",
    category: "housing",
    categoryLabel: "Housing",
    categoryColor: "text-[#0F6E56]",
    categoryBg: "bg-[#E1F5EE]",
    description: "Subsidy on home loan interest for first-time home buyers from economically weaker sections and low income groups. Subsidy ranges from ₹2.67 lakh to ₹2.35 lakh depending on income.",
    keyBenefit: "Home loan interest subsidy of ₹2.35–2.67 lakh",
    maxBenefitAmount: 267000,
    benefitLabel: "₹2.67 lakh interest subsidy",
    eligibility: {
      maxAnnualIncome: 1800000,
      housingStatus: "rent",
      maritalStatus: "any",
    },
    howToApply: "Apply through your bank or housing finance company when taking a home loan. Mention PMAY at the time of application.",
    documentsNeeded: ["Aadhaar card", "Income certificate", "Property documents", "Bank statements 6 months"],
    officialLink: "https://pmaymis.gov.in",
    isNational: true,
  },
  {
    id: "ssy",
    name: "Sukanya Samriddhi Yojana",
    fullName: "Sukanya Samriddhi Yojana",
    category: "women",
    categoryLabel: "Girl Child",
    categoryColor: "text-[#854F0B]",
    categoryBg: "bg-[#FAEEDA]",
    description: "High-interest savings scheme for girl children under 10 years. Currently offers 8.2% annual interest — highest among all government small savings schemes. Completely tax free under Section 80C.",
    keyBenefit: "8.2% annual interest + full tax exemption under 80C",
    benefitLabel: "8.2% guaranteed returns, fully tax free",
    eligibility: {
      requiresGirlChild: true,
      maritalStatus: "any",
    },
    howToApply: "Open at any post office or authorized bank. Minimum deposit ₹250 per year, maximum ₹1.5 lakh per year.",
    documentsNeeded: ["Girl child's birth certificate", "Parent/guardian Aadhaar", "Parent/guardian PAN", "Photo"],
    officialLink: "https://www.indiapost.gov.in/Financial/Pages/Content/Sukanya-Samriddhi-Account.aspx",
    isNational: true,
  },
  {
    id: "pmjjby",
    name: "PM Jeevan Jyoti Bima",
    fullName: "Pradhan Mantri Jeevan Jyoti Bima Yojana",
    category: "insurance",
    categoryLabel: "Life Insurance",
    categoryColor: "text-[#A32D2D]",
    categoryBg: "bg-[#FCEBEB]",
    description: "Life insurance cover of ₹2 lakh for just ₹436 per year. Covers death from any cause. Renewable annually. Available to anyone with a bank account aged 18 to 50.",
    keyBenefit: "₹2 lakh life cover for only ₹436 per year",
    maxBenefitAmount: 200000,
    benefitLabel: "₹2 lakh life cover",
    eligibility: {
      maxAnnualIncome: 9999999,
      minAge: 18,
      maxAge: 50,
      maritalStatus: "any",
    },
    howToApply: "Apply at your bank branch or through net banking. Premium of ₹436 is auto-debited from your account each year.",
    documentsNeeded: ["Bank account", "Aadhaar card"],
    officialLink: "https://jansuraksha.gov.in",
    isNational: true,
  },
  {
    id: "pmsby",
    name: "PM Suraksha Bima",
    fullName: "Pradhan Mantri Suraksha Bima Yojana",
    category: "insurance",
    categoryLabel: "Accident Insurance",
    categoryColor: "text-[#A32D2D]",
    categoryBg: "bg-[#FCEBEB]",
    description: "Accident insurance cover of ₹2 lakh for accidental death or full disability and ₹1 lakh for partial disability. Annual premium is only ₹20. One of the cheapest insurance schemes in the world.",
    keyBenefit: "₹2 lakh accident cover for just ₹20 per year",
    maxBenefitAmount: 200000,
    benefitLabel: "₹2 lakh accident cover",
    eligibility: {
      maxAnnualIncome: 9999999,
      minAge: 18,
      maxAge: 70,
      maritalStatus: "any",
    },
    howToApply: "Apply at your bank branch or net banking. ₹20 is auto-debited annually. Can enroll any time.",
    documentsNeeded: ["Bank account", "Aadhaar card"],
    officialLink: "https://jansuraksha.gov.in",
    isNational: true,
  },
  {
    id: "apy",
    name: "Atal Pension Yojana",
    fullName: "Atal Pension Yojana",
    category: "pension",
    categoryLabel: "Pension",
    categoryColor: "text-[#533AB7]",
    categoryBg: "bg-[#EEEDFE]",
    description: "Guaranteed pension of ₹1,000 to ₹5,000 per month after age 60. Government contributes 50% of your contribution for the first 5 years for eligible subscribers. Best for self-employed and informal sector workers.",
    keyBenefit: "Guaranteed ₹1,000–₹5,000/month pension after 60",
    benefitLabel: "Guaranteed pension for life",
    eligibility: {
      maxAnnualIncome: 9999999,
      minAge: 18,
      maxAge: 40,
      maritalStatus: "any",
    },
    howToApply: "Apply at your bank branch or net banking. Monthly contribution depends on age and chosen pension amount. Earlier you join, lower the monthly contribution.",
    documentsNeeded: ["Bank account with auto-debit", "Aadhaar card", "Mobile number"],
    officialLink: "https://npscra.nsdl.co.in/scheme-details.php",
    isNational: true,
  },
  {
    id: "pmkvy",
    name: "PM Kaushal Vikas",
    fullName: "Pradhan Mantri Kaushal Vikas Yojana",
    category: "business",
    categoryLabel: "Skill Development",
    categoryColor: "text-[#185FA5]",
    categoryBg: "bg-[#E6F1FB]",
    description: "Free skill training in 300+ trades including IT, construction, healthcare, retail, and hospitality. Training centers across India. Certificate recognized by industry. Includes placement assistance.",
    keyBenefit: "Free certified skill training + job placement support",
    benefitLabel: "Free skill training",
    eligibility: {
      maxAnnualIncome: 9999999,
      maritalStatus: "any",
    },
    howToApply: "Register at pmkvyofficial.org or visit nearest PMKVY training center. Select your trade and preferred center.",
    documentsNeeded: ["Aadhaar card", "Bank account", "Photo"],
    officialLink: "https://pmkvyofficial.org",
    isNational: true,
  },
  {
    id: "mudra",
    name: "PM Mudra Yojana",
    fullName: "Pradhan Mantri Mudra Yojana",
    category: "business",
    categoryLabel: "Business Loan",
    categoryColor: "text-[#185FA5]",
    categoryBg: "bg-[#E6F1FB]",
    description: "Collateral-free business loans for small and micro enterprises. Three categories — Shishu up to ₹50,000, Kishore ₹50,000 to ₹5 lakh, Tarun ₹5 lakh to ₹10 lakh. No processing fee for Shishu loans.",
    keyBenefit: "Business loans up to ₹10 lakh without collateral",
    maxBenefitAmount: 1000000,
    benefitLabel: "Up to ₹10 lakh collateral-free loan",
    eligibility: {
      maxAnnualIncome: 9999999,
      maritalStatus: "any",
    },
    howToApply: "Apply at any bank, MFI, or NBFC. Also available online at mudra.org.in. Shishu loans are fastest to process.",
    documentsNeeded: ["Aadhaar", "PAN card", "Business proof or plan", "Bank statements 6 months", "Photo"],
    officialLink: "https://www.mudra.org.in",
    isNational: true,
  },
  {
    id: "nsc",
    name: "National Savings Certificate",
    fullName: "National Savings Certificate (NSC)",
    category: "savings",
    categoryLabel: "Government Savings",
    categoryColor: "text-[#0F6E56]",
    categoryBg: "bg-[#E1F5EE]",
    description: "5-year fixed savings scheme by post office offering 7.7% annual interest compounded yearly. Minimum ₹1,000, no maximum. Interest qualifies for 80C deduction up to ₹1.5 lakh per year.",
    keyBenefit: "7.7% guaranteed returns + 80C tax benefit",
    benefitLabel: "7.7% guaranteed returns",
    eligibility: {
      maxAnnualIncome: 9999999,
      maritalStatus: "any",
    },
    howToApply: "Buy at any post office or online through India Post. Minimum ₹1,000. Available in multiples of ₹100.",
    documentsNeeded: ["Aadhaar card", "PAN card", "Photo"],
    officialLink: "https://www.indiapost.gov.in",
    isNational: true,
  },
  {
    id: "pmfby",
    name: "PM Fasal Bima Yojana",
    fullName: "Pradhan Mantri Fasal Bima Yojana",
    category: "farmers",
    categoryLabel: "Agriculture",
    categoryColor: "text-[#3B6D11]",
    categoryBg: "bg-[#EAF3DE]",
    description: "Crop insurance scheme for farmers covering losses due to natural calamities, pests, and diseases. Premium is only 2% for Kharif crops and 1.5% for Rabi crops. Government pays the rest.",
    keyBenefit: "Crop insurance for just 1.5–2% premium",
    benefitLabel: "Crop insurance scheme",
    eligibility: {
      maxAnnualIncome: 9999999,
      maritalStatus: "any",
    },
    howToApply: "Apply through your bank if you have a crop loan, or directly at nearest Common Service Centre or insurance company office before the cut-off date for each season.",
    documentsNeeded: ["Land records", "Bank account", "Aadhaar", "Sowing certificate"],
    officialLink: "https://pmfby.gov.in",
    isNational: true,
  },
]